### ISSUE TITLE
Feature request: compress existing images

### ISSUE THREAD

**Issue by johanpeters** [pixelstunde/joomla-plg-pxlcompressor#11] opened 2020-01-20 14:56 UTC
Hi,
greate a option to manually / on time run compression on existing images.
select images, select folders (incl. images and subfolder)s.. 

this way you can always arrange compression regardless of supporting the used extention like shops, editors etc..

**Comment by pixelstunde** [comment] 2020-06-14 15:04
Duplicate of #6

**Closed as completed by pixelstunde** 2020-06-14 15:04 UTC
