### ISSUE TITLE
Joomla 3.9.3 upload via images and links not compressing anymore

### ISSUE THREAD

**Issue by Pinkeltje** [pixelstunde/joomla-plg-pxlcompressor#2] opened 2019-03-10 11:54 UTC
Since the update to Joomla 3.9.3 compression is not working anymore when uploading via images and links in article. To make sure it is caused by the update, I've tested the plugin in a clean Joomla 3.9.2 install and in a clean Joomla 3.9.3 install. In 3.9.2 images are compressed in 3.9.3 they are not.

**Comment by pixelstunde** [comment] 2019-03-11 08:51
Sorry, but I can't reproduce the error. I have just tested this in a number of J! 3.9.3 installations which I am supervising. And it is working in all of them. I also tried in a fresh installation and could not find any problems.

![screenshot-testdrivepxlcompressor joomla com-2019 03 11-09-48-10](https://user-images.githubusercontent.com/25514171/54111022-280ba600-43e3-11e9-96ad-e1c0300ed9cf.png)

There was an updated a about a week ago, adding PDF compression support. I also added a checkbox to enable/disable compression services (the only way to disable tinyPNG was to delete the API key in plugin settings before).

Please double check if all settings are correct.

**Comment by Pinkeltje** [comment] 2019-03-11 10:17
Mediamanager is working ok. But in 3.9.2 it worked also in article manager when adding an image through Images and links. And that's not working anymore in 3.9.3.
![20190311-111437](https://user-images.githubusercontent.com/8941310/54116485-2d6eed80-43ef-11e9-8e73-5eb55a8dd84c.png)

**Comment by pixelstunde** [comment] 2019-03-11 10:47
Sorry, but I also can't reproduce this error in article manager. All 4 installations I just checked (including the clean Joomla I set up earlier) did work fine.

Can you please try [Version 1.2](https://github.com/pixelstunde/joomla-plg-pxlcompressor/releases/tag/1.2) and check if the problem persists?

**Comment by Pinkeltje** [comment] 2019-03-11 12:17
Better with 1.2. With TinyMCE compression works 100% including sizing. With JCE image is somewhat compressed but not resized.
**JCE**
![20190311-131129](https://user-images.githubusercontent.com/8941310/54123329-b68e2080-43ff-11e9-950f-55a7d4c4b1f0.png)
**TinyMCE**
![tiny](https://user-images.githubusercontent.com/8941310/54123330-b68e2080-43ff-11e9-8b47-467fb805cd38.png)
Used different images, but both original images are approx. the same size.

**Comment by pixelstunde** [comment] 2019-03-12 06:58
Sorry, JCE does not set mime types, but the plugin is checking them before resizing. So resizing was failing. 

I haven't noticed any problems since the images I uploaded were too small. This issue will be fixed in the next release which will be published as update in Joomla!.

**Closed as completed** 2019-03-12 06:58 UTC
